FROM w251/tensorrtlab05:dev-tx2-4.3_b132

# build this: e.g docker build -t motion -f Dockerfile.opencv-mqtt
# to run this container, do:
# on the host:
# make sure you're in the X environment
# xhost + 
# docker run --rm --privileged -e DISPLAY -v /tmp:/tmp -ti motion bash
# docker run --rm --privileged -e DISPLAY -n face_detector -v ~/Documents/W251/v2/week03/hw_mz/:/home/ -ti motion bash

RUN apt update

ENV DEBIAN_FRONTEND=noninteractive

RUN apt install -y python3-opencv python-pip vim-tiny mosquitto-clients libopencv-dev

RUN pip install paho-mqtt

RUN wget https://github.com/yeephycho/tensorflow-face-detection/blob/master/model/frozen_inference_graph_face.pb?raw=true -O 'data/frozen_inference_graph_face.pb'
